### ISSUE TITLE
"AttributeError: 'Metadata' object has no attribute 'wiki'"

### ISSUE THREAD

**Issue by qerub** [hifiberry/audiocontrol2#2]
```
Traceback (most recent call last):
  File "/opt/audiocontrol2/ac2/metadata.py", line 173, in enrich_metadata
    lastfmdata.enrich_metadata(metadata)
  File "/opt/audiocontrol2/ac2/data/lastfm.py", line 151, in enrich_metadata
    if metadata.wiki is None and "wiki" in trackdata:
AttributeError: 'Metadata' object has no attribute 'wiki'
```

Seems like the code has made some incorrect assumptions about attribute presence.

This is on HiFiBerry OS 20191220.

**Comment by hifiberry** [comment]
Thanks, this should work now with commit https://github.com/hifiberry/audiocontrol2/commit/47f12c76b83df8e14d5f5ddc6fc9d1f6587d58d5

**Comment by qerub** [comment]
There was already a `self.wiki = None` a couple of lines higher up: https://github.com/hifiberry/audiocontrol2/commit/524ad26e80b4dbb4f3f59f200b120825a486ef2a#diff-b83c74b25e1e5127e48eecdf59a14ad7R67

**Comment by hifiberry** [comment]
Ahhh, looks like I fixed a bug that was already fixed ;-)

**Comment by qerub** [comment]
I don't know about that… I had `self.wiki = None` in my locally installed copy but still got the reported exception.

**Comment by hifiberry** [comment]
Strange. Do you still see this with the latest HiFiBerryOS release? I haven't seen this.

**Comment by qerub** [comment]
I haven't updated yet. Will get back to you once I have!

**Comment by qerub** [comment]
Still reproducible with HiFiBerryOS 20200127. New traceback with updated line numbers and some context:

```
DEBUG: http - retrieved from cache: http://ws.audioscrobbler.com/2.0/?method=track.getInfo&api_key=7d2431d8bb5608574b59ea9c7cfe5cbd&artist=The%20Coathangers&track=Nosebleed%20Weekend&format=json
WARNING: metadata - error when retrieving data from last.fm
ERROR: metadata - 'Metadata' object has no attribute 'wiki'
Traceback (most recent call last):
  File "/opt/audiocontrol2/ac2/metadata.py", line 183, in enrich_metadata
    lastfmdata.enrich_metadata(metadata)
  File "/opt/audiocontrol2/ac2/data/lastfm.py", line 151, in enrich_metadata
    if metadata.wiki is None and "wiki" in trackdata:
AttributeError: 'Metadata' object has no attribute 'wiki'
```

**Comment by hifiberry** [comment]
Ok, I see it here also. Need toi add more logging to find out where this comes from.

**Comment by hifiberry** [comment]
I'm still not sure how this happens, but I have added some code in the lastfm module to prevent this. This will be included in the HiFiBerryOS february 2020 release

**Comment by qerub** [comment]
OK! Feel free to close this issue. Advantageously with a link to the commit/patch.

**Comment by hifiberry** [comment]
I haven't seen this anymore. I guess, it's fixed now.
